[package]
name = "smee"
version = "0.1.0"
description = "Smee is a Git hooks manager."
edition = "2024"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/lpireyn/smee/"

[[bin]]
name = "smee"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"
