[package]
name = "smee"
version = "0.3.0"
authors.workspace = true
description = "Smee is a Git hooks manager."
edition.workspace = true
readme = "../../README.md"
license.workspace = true
repository.workspace = true
default-run = "smee"

[[bin]]
name = "smee"
path = "src/main.rs"

[dependencies]
clap.workspace = true
eyre.workspace = true
is_executable = "1.0"
log.workspace = true
logger.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
tempfile = "3.23"
